---
- name: setup
  hosts: all
  become: yes

- import_playbook: playbooks/bootstrap.yml
- import_playbook: playbooks/apt-install.yml
# - import_playbook: playbooks/apt-update.yml
- import_playbook: playbooks/docker.yml
# - import_playbook: playbooks/nvm.yml
- import_playbook: playbooks/rbenv.yml
