---
- name: setup
  hosts: all
  become: yes

- import_playbook: playbooks/bootstrap.yml
- import_playbook: playbooks/apt-install.yml

- import_playbook: playbooks/bin-hashicorp.yml

- import_playbook: playbooks/docker.yml

- import_playbook: playbooks/goenv.yml
- import_playbook: playbooks/rbenv.yml
- import_playbook: playbooks/tfenv.yml
