---
- name: apt install
  hosts: all
  become_method: sudo

  tasks:
    - name: apt install
      state: present
      apt:
        pkg:
          - curl
          - git
          - htop
          - ipcalc
          - lsof
          - mc
          - nmap
          - rsync
          - stow
          - tig
          - tmux
          - ufw
          - vim
          - wget
