---
- name: apt-update
  hosts: all
  become: yes
  serial: 1

  tasks:
  - name: apt update
    apt:
      update_cache: yes
  - name: apt safe-upgrade
    command: aptitude safe-upgrade -y
  - name: apt autoremove
    apt:
      autoremove: yes
  - name: apt autoclean
    apt:
      autoclean: yes
  - name: apt clean
    command: apt clean -y
  - name: apt purge
    command: aptitude purge ~c -y
