---
- name: bin-hashicorp
  hosts: all
  serial: 1

  pre_tasks:
  - name: bin => mkdir
    file:
      path: $HOME/.bin
      state: directory
  - name: bin => configure
    blockinfile:
      path: '~/.bashrc'
      marker: "# {mark} ANSIBLE MANAGED BLOCK"
      block: |
        export PATH=$PATH:~/.bin
      insertbefore: EOF

  tasks:
  - name: bin => consul
    tags: consul
    unarchive:
      src: https://releases.hashicorp.com/consul/1.6.2/consul_1.6.2_linux_amd64.zip
      dest: $HOME/.bin
      remote_src: yes
      mode: 0755
  - name: bin => nomad
    tags: nomad
    unarchive:
      src: https://releases.hashicorp.com/nomad/0.10.2/nomad_0.10.2_linux_amd64.zip
      dest: $HOME/.bin
      remote_src: yes
      mode: 0755
  - name: bin => packer
    tags: packer
    unarchive:
      src: https://releases.hashicorp.com/packer/1.4.5/packer_1.4.5_linux_amd64.zip
      dest: $HOME/.bin
      remote_src: yes
      mode: 0755
  - name: bin => terraform
    tags: terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.16/terraform_0.12.16_linux_amd64.zip
      dest: $HOME/.bin
      remote_src: yes
      mode: 0755
  - name: bin => vagrant
    tags: vagrant
    unarchive:
      src: https://releases.hashicorp.com/vagrant/2.2.6/vagrant_2.2.6_linux_amd64.zip
      dest: $HOME/.bin
      remote_src: yes
      mode: 0755
  - name: bin => vault
    tags: vault
    unarchive:
      src: https://releases.hashicorp.com/vault/1.3.0/vault_1.3.0_linux_amd64.zip
      dest: $HOME/.bin
      remote_src: yes
      mode: 0755
