---
- name: bin-bosh
  hosts: all
  serial: 1

  pre_tasks:
  - name: bosh => install `bosh create-env` required packages
    become: yes
    apt:
      update_cache: yes
      state: present
      pkg:
        - build-essential
        - libreadline6
        - libreadline6-dev
        - libsqlite3-dev
        - libssl-dev
        - libxml2-dev
        - libxslt-dev
        - libyaml-dev
        - openssl
        - ruby
        - ruby-dev
        - sqlite3
        - zlib1g-dev
        - zlibc
  - name: bosh => mkdir bin
    file:
      path: $HOME/.bin
      state: directory

  tasks:
  - name: bosh => bosh-bootloader
    get_url:
      url: https://github.com/cloudfoundry/bosh-bootloader/releases/download/v8.4.0/bbl-v8.4.0_linux_x86-64
      dest: $HOME/.bin/bbl
      mode: 0755
  - name: bosh => bosh-cli
    get_url:
      url: https://github.com/cloudfoundry/bosh-cli/releases/download/v6.1.1/bosh-cli-6.1.1-linux-amd64
      dest: $HOME/.bin/bosh
      mode: 0755
