---
- name: docker
  hosts: all
  become: yes
  serial: 1

  pre_tasks:
  - name: docker => install required packages
    apt:
      update_cache: yes
      state: present
      pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

  tasks:
  - name: docker => add gpg key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: docker => add apt repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
      state: present
  - name: docker => apt update
    apt:
      update_cache: yes
  - name: docker => install packages
    apt:
      update_cache: yes
      state: present
      pkg:
        - containerd.io
        - docker-ce
        - docker-ce-cli
  - name: docker => add user to docker group
    user:
      name: gabriel
      groups: docker
      append: true
