---
- name: hashicorp
  hosts: all
  serial: 1

  pre_tasks:
  - name: bin => mkdir
    file:
      path: $HOME/.bin
      state: directory
  - name: bin => configure
    blockinfile:
      path: '~/.bashrc'
      marker: "# {mark} ANSIBLE MANAGED BLOCK BINUTILS"
      block: |
        # binutils
        export PATH=$PATH:~/.bin
      insertbefore: EOF

  tasks:
  - name: hashicorp => consul
    unarchive:
      src: https://releases.hashicorp.com/consul/1.4.4/consul_1.4.4_linux_amd64.zip
      dest: $HOME/.bin
      remote_src: yes
      mode: 0755
  - name: hashicorp => nomad
    unarchive:
      src: https://releases.hashicorp.com/nomad/0.8.7/nomad_0.8.7_linux_amd64.zip
      dest: $HOME/.bin
      remote_src: yes
      mode: 0755
  - name: hashicorp => terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip
      dest: $HOME/.bin
      remote_src: yes
      mode: 0755
  - name: hashicorp => vault
    unarchive:
      src: https://releases.hashicorp.com/vault/1.1.0/vault_1.1.0_linux_amd64.zip
      dest: $HOME/.bin
      remote_src: yes
      mode: 0755
