---
- name: lastpass
  hosts: all
  become: yes
  serial: 1

  pre_tasks:
  # For Debian (testing/experimental) and Ubuntu >= 18.04
  - name: lastpass => install required packages
    apt:
      update_cache: yes
      state: present
      pkg:
        - bash-completion
        - build-essential
        - ca-certificates
        - cmake
        - libcurl4
        - libcurl4-openssl-dev
        - libssl-dev
        - libssl1.1
        - libxml2
        - libxml2-dev
        - pkg-config
        - xclip
  tasks:
  - name: bin => mkdir
    file:
      path: /tmp/lastpass-cli-1.3.3
      state: directory
  - name: lastpass => download
    unarchive:
      src: https://github.com/lastpass/lastpass-cli/releases/download/v1.3.3/lastpass-cli-1.3.3.tar.gz
      dest: /tmp/lastpass-cli-1.3.3
      remote_src: yes
  - name: lastpass => build
    make:
      chdir: /tmp/lastpass-cli-1.3.3
  - name: lastpass => install
    make:
      target: install
      chdir: /tmp/lastpass-cli-1.3.3
  - name: lastpass => verify
    command: lpass --version
