---
- name: virtualbox
  hosts: all
  become: yes
  serial: 1

  tasks:
  - name: virtualbox => add gpg key 2016
    apt_key:
      url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
      state: present
  - name: virtualbox => add gpg key
    apt_key:
      url: https://www.virtualbox.org/download/oracle_vbox.asc
      state: present
  - name: virtualbox => add apt repository
    apt_repository:
      repo: deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian bionic contrib
      state: present
  - name: virtualbox => apt update
    apt:
      update_cache: yes
  - name: virtualbox => install packages
    apt:
      update_cache: yes
      state: present
      pkg:
        - virtualbox-6.0
